version: '3.10.13'

services:

  dash:
    #command: python3 main.py
    image: carapp:a3
    platform: linux/x86_64
    build: 
      context: .
      dockerfile: .Dockerfile
    ports:
      - 9001:80
    volumes:
      - ./code:/root/code
      - ./.vscode-server:/root/.vscode-server
    environment:
      - HOST=0.0.0.0
      - PORT=80
    env_file:
      - .env